### ISSUE TITLE
Support reproducible downloads

### ISSUE THREAD

**Issue by EricCrosson** [EricCrosson/install-github-release-binary#26]
Consider the caller who cares about reproducibility:

```yaml
- uses: EricCrosson/install-github-release-binary@f8eb4478eab436937f635434489bb7c7a2893fee
  with:
    targets: EricCrosson/retry@v1.0.0
```

We can pin the sha of this action, but there is no way to pin the sha of the target.

Possible solutions:

1. support specifying the sha of the release (this information [is available] in the GitHub API response we pull)
   
   ```yaml
   - uses: EricCrosson/install-github-release-binary@f8eb4478eab436937f635434489bb7c7a2893fee
     with:
       targets: EricCrosson/retry@<sha>
   ```

1. support checksum verification of the downloaded binary

   ```yaml
   - uses: EricCrosson/install-github-release-binary@f8eb4478eab436937f635434489bb7c7a2893fee
     with:
       targets: EricCrosson/retry@<checksum> # ? awkward
   ```

[is available]: https://github.com/EricCrosson/install-github-release-binary/blob/115d6ef985272c65333a6aac1a24aca95cab4fb4/test/no-release-candidate-workflow.json#L7

**Comment by louib-bitgo** [comment]
With the `EricCrosson/retry@<checksum>` syntax, the checksum could be mistaken for a sha. I would suggest using another parameter for the checksum. This would also make it explicit which sha algorithm is expected. For example:
```
- uses: EricCrosson/install-github-release-binary@f8eb4478eab436937f635434489bb7c7a2893fee
  with:
    targets: EricCrosson/retry@v1.2.3
    sha256: 1ddfb769eb0b8876bc570e25580e6a53afcf973362ee1ee4b54a807da2e5eed7
```

**Comment by EricCrosson** [comment]
I am leaning towards option 1, because `targets` already takes a list:

```yaml
- uses: EricCrosson/install-github-release-binary@f8eb4478eab436937f635434489bb7c7a2893fee
  with:
    targets: |
      DeepBlue/master-mind@v42
      EricCrosson/retry@<sha>
```

I don't want to go down the route of embedding strings-of-yaml or other structured input

**Comment by EricCrosson** [comment]
Turns out pinning a release to a specific sha is not truly reproducible, because the release's artifacts can be edited at any time.

The only way I know to ensure reproducibility is with a content-based checksum. I'll re-open this issue and will consider reverting e9c333130ebad0fe7b5ca58162c7444a51b91731 to keep the API surface-area low

**Comment by EricCrosson** [comment]
^ This is the commit that backs out support for specifying a target with a commit sha, since that was ineffective.

**Comment by EricCrosson** [comment]
I'm exploring two different syntax (TIL that "syntax" can be plural!) to specify both a checksum and a version target.

First, embedding a structured input format in a string:

```yaml
- uses: EricCrosson/install-github-release-binary@v2
  with:
    targets: |
      {
        "target": "EricCrosson/flux-capacitor@v3.1.1",
        "checksum": "xxxxxxxxxxxxxxxxxxxxxxxxx",
      }
```

I dislike the projection of this structured language into a string, which may present a poor user experience (in terms of syntax highlighting, verbosity). Also, can I beat `targets` for the input name and a redundant `target` in the data format?

Second, what about environment variables to specify the optional checksum?

```yaml
- uses: EricCrosson/install-github-release-binary@v2
  with:
    targets: |
      EricCrosson/flux-capacitor@v3.1.1
  env:
    SHA256_ERICCROSSON_FLUX_CAPACITOR: xxxxxxxxxxxxxxxxxxxxxxxxx
```

Third (just came to me) what about overloading the single-string syntax?

```yaml
- uses: EricCrosson/install-github-release-binary@v2
  with:
    targets: |
      EricCrosson/flux-capacitor@v3.1.1#xxxxxxxxxxxxxxxxxxxxxxxxx
```

If you have input or suggestions, I'd love to hear it!
